name: news_app_clean_architecture
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  # Ampliamos el rango para permitir versiones nuevas de Firebase pero mantener compatibilidad
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  ionicons: ^0.1.2

  # State management
  flutter_bloc: ^8.1.3 # Versión estable compatible
  equatable: ^2.0.5
  get_it: ^7.6.0
  
  # Error handling (NECESARIO PARA TU CÓDIGO NUEVO)
  dartz: ^0.10.1
  
  # DateFormat
  intl: ^0.18.1

  # Database
  floor: ^1.4.2

  # API Request (VERSIONES ANTIGUAS PARA NO ROMPER EL PROYECTO BASE)
  retrofit: ^3.0.1 
  dio: ^4.0.6      

  # Firebase (ACTUALIZADO PARA ARREGLAR BUG DE WINDOWS)
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.0
  firebase_storage: ^11.6.0 

  # Hooks
  flutter_hooks: ^0.18.6

  # Cached image 
  cached_network_image: ^3.3.0
  
  # Image Picker (PARA TU NUEVA FEATURE)
  image_picker: ^1.0.4

  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^4.0.0 # Compatible con retrofit 3
  floor_generator: ^1.4.2
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300